### ISSUE TITLE
Upgrade signalbub to wss:// ?

### ISSUE THREAD

**Issue by DougAnderson444** [datproject/sdk#16]
When I try to use the SDK to do 
`const { Hypercore } = SDK()`
over HTTPS on [esnextbin](https://esnextb.in/?gist=bedb33fde08a718d9a8b12972ccfae80), I get this error:
```
was loaded over HTTPS, but attempted to connect to the insecure 
WebSocket endpoint 'ws://signalhubws.mauve.moe/discovery-swarm-web'. 
This request has been blocked; this endpoint must be available over WSS.
```
Should `ws://signalhubws.mauve.moe/discovery-swarm-web` be sent over wss?

**Comment by RangerMauve** [comment]
Weird. It should be auto-detecting HTTPS pages and setting the proper protocol. 🙃 https://github.com/RangerMauve/discovery-swarm-web/blob/master/index.js#L38

**Comment by RangerMauve** [comment]
Might be a bug in there somewhere.

**Comment by RangerMauve** [comment]
Gonna close this for now, feel free to reopen if it's actively a problem again
