### ISSUE TITLE
Cross Origin Request Blocked

### ISSUE THREAD

**Issue by urgent** [datproject/sdk#21]
**What I Wanted**
DatArchive.load and read file per https://github.com/datproject/sdk#apiexamples-promise

**What I Did**

index.js:
```
// Auto-detects sane defaults based on your environment
// Uses Beaker's APIs if they are if they are available
// DatArchive is the same as Beaker
// https://beakerbrowser.com/docs/apis/dat
const { DatArchive } = require("dat-sdk/auto");

(async function() {
  const archive = await DatArchive.load("dat://dat.foundation");

  const someData = await archive.readFile("/dat.json", "utf8");

  console.log("Dat foundation dat.json:", someData);
})();
```

`browserify -d index.js > test-bundle.js`

index.html:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="/test-bundle.js" defer></script>
  </head>
  <body>
    <div></div>
  </body>
</html>
```

**What I Got**

> Firefox console output:
> TypeError: NetworkError when attempting to fetch resource.
> Firefox can’t establish a connection to the server at ws://localhost:3472/. stream.js:64
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://gateway.mauve.moe/undation/.well-known/dat. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
> 
> TypeError: NetworkError when attempting to fetch resource.

**Comment by RangerMauve** [comment]
Oh wow. I think it's an error parsing `dat.foundation`. Could you try out `dat://beakerbrowser.com` to see if it works?

**Comment by urgent** [comment]
No, still no luck:
![image](https://user-images.githubusercontent.com/1377758/66407840-e7e1c580-e9bb-11e9-91c5-d8bebbb6736e.png)

![image](https://user-images.githubusercontent.com/1377758/66407906-ffb94980-e9bb-11e9-88c7-41c80efd84dd.png)

**Comment by RangerMauve** [comment]
Gonna try to reproduce it on my end. Are you using the latest version of the SDK?

**Comment by RangerMauve** [comment]
Oh dang! Thank you so much for bringing this up. I think I found the problem! :D

**Comment by RangerMauve** [comment]
Could you try installing the latest version on master and seeing if it works?

`npm i -s datproject/sdk`

**Comment by urgent** [comment]
Error: File not found

**Comment by urgent** [comment]
Closed with:

https://github.com/datproject/sdk/commit/0ba4031d360f51cc977e15b652c0932e6fa5af65

**Comment by RangerMauve** [comment]
Awesome! :D

**Comment by urgent** [comment]
@RangerMauve I am still getting that file not found error.

I closed it while I tested on creating an archive of my own, think that would fix it like there were different files in a new archive, but no luck.

I'm just getting started with dat, and will debug this too on my side.

**Comment by RangerMauve** [comment]
Ok, this might sound dumb. But try adding in a delay of like 3 seconds before doing a readdir. :P

It might just not be loading the data quickly enough.

**Comment by RangerMauve** [comment]
I had [a bunch of code](https://github.com/datproject/sdk/blob/master/promise.js#L63) in place to account for such a circumstance, but it looks like it still needs some work.

You can add something like this after the initial `DatArchive.load()` call:

```js
await new Promise((resolve) => setTimeout(resolve, 3000))
```

That'll wait for 3 seconds for it to sync up with peers.

**Comment by RangerMauve** [comment]
I think I found something that'll help. I'll try releasing it tomorrow after doing a thorough regression test.

**Comment by urgent** [comment]
Yes that 3 second wait worked great. Thank you!
