### ISSUE TITLE
Hypercore Secret Key option

### ISSUE THREAD

**Issue by urgent** [datproject/sdk#27]
My platform starts up a new container for each build and I keep loosing write permissions. 

In the dat-sdk, is it possible to:

  -  access the secret key from the object returned from DatArchive.create
  -  set it as the secretKey option in DatArchive.load per https://github.com/mafintosh/hypercore#api 

I was thinking of something like:
```
const myArchive = await DatArchive.create({
  title: 'My Archive'
})

const archive = await DatArchive.load(myArchive.url, {secretKey: myArchive.secretKey})
```

That way, I can set `secretKey` as an env variable, and maintain write permissions between containers.

**Comment by RangerMauve** [comment]
Would you be comfortable with an API like 'archive.getSecretKey()` which returns a promise?

cc @pfrazee since this might be a divergence from Beaker's API.

**Comment by pfrazee** [comment]
Sure go ahead

**Comment by RangerMauve** [comment]
Cool, I might get to it next week, but in the meantime a PR with a unit test would be very much welcome. It could look something like

```js
async getSecretKey() {
await this._loadPromise
return this._archive.secretKey
}
```
