### ISSUE TITLE
How to close DatArchive

### ISSUE THREAD

**Issue by urgent** [datproject/sdk#28]
How may I run this code so that the node process ends?

I run it with `node dat.js`, and the process hangs.

> dat.js

```
const { DatArchive } = require('dat-sdk/auto')
const read = async () => {
  const archive = await DatArchive.load('dat://dat.foundation')

  const someData = await archive.readFile('/dat.json', 'utf8')

  console.log(someData)
}

read()
```

Thank you!

**Comment by RangerMauve** [comment]
If you change your import to `const { DatArchive, destroy } = require('dat-sdk/auto')` you can invoke the `destroy()` function to clean up all resources.

**Comment by RangerMauve** [comment]
This doesn't delete your storage. It just closes all the archives and the swarm

**Comment by urgent** [comment]
Works great, thank you!
