### ISSUE TITLE
Chrome Security Prompt: Store Files on this Device ?

### ISSUE THREAD

**Issue by KrishnaPG** [datproject/sdk#29]
Running this below example code from the ReadMe is prompting security alert as shown below. Since this example code apparently does not much, this prompt is very alarming. 

![image](https://user-images.githubusercontent.com/4610831/69020187-ae986e80-09d9-11ea-8004-3f10fdb4d219.png)
````
  const discoveryCoreKey = 'dat://bee80ff3a4ee5e727dc44197cb9d25bf8f19d50b0f3ad2984cfe5b7d14e75de7'
  const discoveryCore = new Hypercore(discoveryCoreKey, {
    extensions: ['discovery']
  });    
````
**Question**: 

How to specify that dat SDK should use IDB / [localForage ](https://github.com/localForage/localForage)or its equivalent instead of FileSystemAPI?

**Comment by RangerMauve** [comment]
You can pass a `storage` option in the constructor, or use `persist: false` when initializing the archive.

cc @serapath who encountered this issue, too.
