### ISSUE TITLE
Spring release plan 

### ISSUE THREAD

**Issue by okdistribute** [datproject/sdk#31]
Like spring cleaning but spring releasing!

@RangerMauve, want to make a plan around how to reduce the 'TODO' items in the README and start calling this module 'v1.0'/done, and hopefully deprecate other modules that it replaces (i.e., dat-js/dat-node)? Happy to jump on a call sometime!

**Comment by RangerMauve** [comment]
Honestly, as it is now, it's good enough for a V 1.0. I'd just need to build up some more docs. And then have a 2.0 once the Dat2 stuff stabilizers. Also down for a call to talk about it.

Also down for feedback for ideas of what should be done before 1.0 from the general community.

**Comment by okdistribute** [comment]
1. Move parts of Roadmap from README to issues
2. 1.0 API reference in README
3. Publish 1.0 on npm
4. Deprecate dat-js/dat-node 
5. Walkthrough https://docs.datproject.org and update references to dat-js/node/sdk

**Comment by RangerMauve** [comment]
Working on this now. Did some fixing up, put the roadmap into issues, updated the README a bit.

**Comment by RangerMauve** [comment]
Got the API docs in, gonna look at them some more, then publish 1.0.

Hoping to populate the docs site with some basic SDK examples.

**Comment by RangerMauve** [comment]
Published on NPM. Gonna look into deprecation more.

**Comment by RangerMauve** [comment]
Archived dat-node and dat-js. Working on documentation right now. https://github.com/datproject/docs/tree/dat-sdk

Started by replacing all the references to dat-js and dat-node. Now replacing "usingdat-browser.md" with "usingdat-sdk.md"

**Comment by RangerMauve** [comment]
Opened a PR for the docs. Waiting to get a review so it can be merged in and put on the live website. :)

Anyone with the time is welcome to review. https://github.com/datproject/docs/pull/170

**Comment by RangerMauve** [comment]
Cool, I guess this is all done! :D
