### ISSUE TITLE
Document the differences between the sdk and dat-node

### ISSUE THREAD

**Issue by martinheidegger** [datproject/sdk#48]
I recently tried to use the dat-sdk as i would have used dat-node and noticed that both the data storage structure and the synchronization has changed entirely. It would be good if there was documentation about it.

**Comment by okdistribute** [comment]
sdk is for building an app, more diy, dat-node is for building something on the filesystem.

dat-node could be built with the sdk, if we did it in opposite order.

does that make sense?

**Comment by martinheidegger** [comment]
dat-node is not building on dat sdk and its not clear whether or not dat-node should still be used, as:

> dat-node could be built with the sdk, if we did it in opposite order.

... which means that dat-node is not (yet?) built based on the dat-sdk (and @RangerMauve mentioned that this might be pretty tough?)

**Comment by okdistribute** [comment]
there isn't currently funds to support that work

**Comment by RangerMauve** [comment]
Gonna close this for now unless more folks have questions. 😁
