### ISSUE TITLE
how to load DatArchive in writable state ?

### ISSUE THREAD

**Issue by k2s** [datproject/sdk#49]
```
const archive = await DatArchive.load(datURL, {
        secretKey,
        persist: false
})
console.log((await archive.readdir('/')).length)
await archive.writeFile('/index.html', '<h1>Hello World!</h1>')
```

* if `secretKey===null` then on my dat it prints number 3 and `writeFile` fails with error `Cannot write to this archive ; Not the owner`
* if I do the same, with `secretKey` set to value returned by `dat keys export` it prints number 0 and write doesnt fail, but it doesn't get created in original repository

is this bug or how should I provide secretKey to be able to write to the repository ?

**Comment by RangerMauve** [comment]
Hey! I think you can use the `isOwner` flag in the data returned by [archive.getInfo](https://beakerbrowser.com/docs/apis/dat#getinfo)

**Comment by k2s** [comment]
Thank you for answer. I don't need to read information, but to set the archive to writable mode.

I forgot to mention that I use it in NodeJS.

**Comment by RangerMauve** [comment]
In node.js if you created the archive with DatArchive it should be loading the secret key automatically. Otherwise you need to pass in the secret key each time to make it writable.

**Comment by k2s** [comment]
I have created the dat archive with command line tool `dat` on different PC. `dat sync` is running there. Now I want to connec to this dat repository. which works fine until I provide `secretKey`.

The value I set to secretKey is string output from command `dat keys export`. With this key provided the DatArchive stops to even to list the content of the archive which works without the `secretKey` option.

**Comment by RangerMauve** [comment]
Dat breaks if you try to set the secret key on more than one device at a time. If you want to update an archive from more than one machine, I suggest looking into [Kappa-Drive](https://ledger-git.dyne.org/CoBox/kappa-drive) or the mounts feature in [Hyperdrive-daemon](https://github.com/andrewosh/hyperdrive-daemon)
