### ISSUE TITLE
issues with bundling for web 

### ISSUE THREAD

**Issue by karlmoubarak** [datproject/sdk#57]
I am happy to try the new version of the sdk.  When bundling for web, I ran into some issues. This is all very new to me, so I am not sure where things went wrong.

1. Compiling with build:
```
git clone git@github.com:datproject/sdk.git
cd sdk
npm install
npm run build
```
With `dat-sdk-bundle.js` linked in my html page, my browser logs this error:
```
dat-sdk-bundle.js:64222 Uncaught Error: No native build was found for platform=browser arch=javascript runtime=node abi=undefined uv= libc=glibc
    at Function.load.path (dat-sdk-bundle.js:64222)
    at load (dat-sdk-bundle.js:64187)
    at Object.<anonymous> (dat-sdk-bundle.js:64160)
    at Object.427.node-gyp-build (dat-sdk-bundle.js:64164)
    at o (dat-sdk-bundle.js:1)
    at dat-sdk-bundle.js:1
    at Object.<anonymous> (dat-sdk-bundle.js:51584)
    at Object.317../cipher-state (dat-sdk-bundle.js:52085)
    at o (dat-sdk-bundle.js:1)
    at dat-sdk-bundle.js:1
```

2. With Browserify:
```
npm install --save-dev browserify
npm install --save dat-sdk@next
browserify index.js > bundle.js
```
Npm could not find modules 'babelify' and '@babel/core', so after installing them manually and bundling again, I got back a bundle.js and could link it my webpage. My browser logs the same error as above.

3. With Webpack:

In my working directory, I installed the sdk, webpack, and webpack-cli with `npm install --save dat-sdk webpack webpack-cli`, and used the same webpack.config.js as the one in the documentation. This attempt did not make it to the browser, with the `./node_modules/.bin/webpack` command logging this error for every instance of `util` in the sdk:
```
ERROR in ./node_modules/browserify-sign/node_modules/readable-stream/lib/_stream_readable.js
Module not found: Error: Can't resolve 'util' in '/Users/km/Desktop/HOMESERVER/tryouts/hyperdrive-test-5-webpack/node_modules/browserify-sign/node_modules/readable-stream/lib'
 @ ./node_modules/browserify-sign/node_modules/readable-stream/lib/_stream_readable.js 60:16-31
 @ ./node_modules/browserify-sign/node_modules/readable-stream/readable-browser.js
 @ ./node_modules/browserify-sign/browser/index.js
 @ ./node_modules/crypto-browserify/index.js
 @ ./node_modules/corestore-swarm-networking/index.js
 @ ./node_modules/dat-sdk/index.js
 @ ./index.js
```
Although `./node_modules/util/util.js` does exist. I don't know why this is happening.

(npm v6.14.5, node v12.18.1, and Google Chrome v83 on macOS 10.15.5)

**Comment by RangerMauve** [comment]
Thank you for opening the issue! Just had a chance to look into it and it seems I've forgotten to add the babelify transform to the `npm run build` command. Could you try using `git pull` to get the latest version of the repo and trying again?

Not sure what the webpack issue is, we might need to copy all the aliases that browserify provides by default here: https://github.com/browserify/browserify/blob/master/lib/builtins.js

**Comment by karlmoubarak** [comment]
With the latest fixes, everything works. I don't get anymore errors. Thanks again, Mauve! 👩‍💻

**Comment by RangerMauve** [comment]
Sweet, thank you for helping work though this. 💜
