### ISSUE TITLE
Different Extensions per Hyperdrive/Hypercore

### ISSUE THREAD

**Issue by martinheidegger** [datproject/sdk#6]
It would probably result in unexpected behavior if different Hyperdrives/Hypercores used different extensions:

```javascript
const sdk = new SDK()
sdk.Hypercore({extensions: ['a']})
sdk.Hypercore(..., {extensions: ['b']})
```

as the first hyper* would add the extension a to the swarm but the second hypercore would have a & b (even though only a was specified). And while the first one would expect it only had a connecting to it, in the protocol it would broadcast both the availability of a and b.

For the time being I think the quickest solution to this would be that `extensions` are added as option to the swarm and explicitly forbidden as option to a core/drive.

**Comment by RangerMauve** [comment]
Could you elaborate more on why sharing extensions should be avoided?

**Comment by RangerMauve** [comment]
Gonna close this for now. 😁
