### ISSUE TITLE
Cannot build bundle for browsers

### ISSUE THREAD

**Issue by nishp77** [datproject/sdk#62]
Steps followed were the same as mentioned in Readme file

Result: 
![image](https://user-images.githubusercontent.com/35785259/94162386-43ff5d00-fe4c-11ea-95e0-667d02339b7e.png)

**Comment by DougAnderson444** [comment]
you need to `npm install` the alias dependencies
```
npm install --save-dev util 
npm install --save @geut/sodium-javascript-plus hyperswarm-web
```
I've added to the README to clarify this:
[https://github.com/datproject/sdk/pull/63](https://github.com/datproject/sdk/pull/63)

**Comment by nishp77** [comment]
@DougAnderson444 I have installed the dependencies but still showing the same error

**Comment by RangerMauve** [comment]
@nishp77 Did you do an `npm install` upon cloning? @tinchoz49 did something change in your sodium fork?

**Comment by nishp77** [comment]
@RangerMauve yes after cloning just did npm i

**Comment by RangerMauve** [comment]
K, I gotta focus on work for a few hours, but I'll set a reminder on my calendar to check this out tonight (~20:00 ET ish)

**Comment by RangerMauve** [comment]
Thank you for opening the issue and for your patience! Hopefully once I tack a crack at it it'll be fixed for good. 😁

**Comment by tinchoz49** [comment]
Hey @RangerMauve , no, didn't do any change later

**Comment by RangerMauve** [comment]
Try the latest master branch or version 2.8.0 😁
