### ISSUE TITLE
Browser test failing (Storage / RAW)

### ISSUE THREAD

**Issue by DougAnderson444** [datproject/sdk#66]
When I build the test and open in the browser, it fails. This is what i get:

```
test-bundle.js:66097 Uncaught (in promise) Error: Not opened
    at Request._openAndNotClosed (test-bundle.js:66097)
    at Request._run (test-bundle.js:66120)
    at RandomAccess.run (test-bundle.js:66025)
    at RandomAccess.write (test-bundle.js:65979)
    at Request._callback (test-bundle.js:22236)
    at Request.callback (test-bundle.js:66091)
    at nextTickCallback (test-bundle.js:66185)
    at Item.run (test-bundle.js:63440)
    at drainQueue (test-bundle.js:63404)
```

I haven't been able to `persist: true` in the browser for a while. For some reason the random-access-storage isn't opening? I'm not sure how to troubleshoot this. :disappointed: 

Browser: Chrome 85 on Windows
sdk `v 2.8.1`

**Comment by DougAnderson444** [comment]
![image](https://user-images.githubusercontent.com/6699901/94500983-aea6f480-01ce-11eb-86d8-ca6a37370ad7.png)

**Comment by DougAnderson444** [comment]
sdk `v 2.8.1`

**Comment by DougAnderson444** [comment]
My finger slipped. This is still and issue :sheep:

**Comment by RangerMauve** [comment]
I think the issue is happening in here: https://github.com/random-access-storage/random-access-chrome-file

No clue what could be causing it though.... 😅  Actually, I'm not sure, but I'm guessing that Chrome would be following the random-access-chrome-file code path.

**Comment by RangerMauve** [comment]
Are you using private browsing by any chance?

**Comment by DougAnderson444** [comment]
No private browsing, just an ad blocker.

**Comment by RangerMauve** [comment]
I had it working in Agregore last week, at least the web version of the SDK was working, I think. Yeah, I'll try to check out the RAW tests later this week. (maybe thursday/friday?)

**Comment by RangerMauve** [comment]
The SDK seems to be working okay in Firefox and Chromium based browsers as of the latest release.

Feel free to reopen if you're still having issues.
