### ISSUE TITLE
Hyperdrive not replicating using the dat-sdk bundle.js

### ISSUE THREAD

**Issue by nishp77** [datproject/sdk#67]
Trying to make an Ionic App:-

First Peer- generated the drive and got the key 

Second Peer- took the key from the first peer but showed that it couldn't find the drive

**Comment by RangerMauve** [comment]
Are both of these being served from web pages with WebRTC support? Would you mind providing the code where you create the drive and where you get the drive to the other peer?

Have you double checked that the second `drive.key` is being set to the correct value?

**Comment by RangerMauve** [comment]
@nishp77 Did you get it to work?
