### ISSUE TITLE
Uncaught (in promise) Error: Not opened

### ISSUE THREAD

**Issue by glowkeeper** [datproject/sdk#70]
The very first thing I try to do with the sdk gives an error:

```
const SDK = require('dat-sdk')
const sdk = await SDK()
```

I get _Uncaught (in promise) Error: Not opened_ :

```
_openAndNotClosed
```

What am I doing wrong?

**Comment by glowkeeper** [comment]
ps. if I run `dat share mySharedDir/ --http` then browse `http://localhost:8080`, I get a list of all my shared files. Essentially, that's all I want to do above, so I know it's possible :)

**Comment by glowkeeper** [comment]
I've attached a screengrab of the console:

<img width="1440" alt="Screenshot 2020-10-28 at 15 46 47" src="https://user-images.githubusercontent.com/9264929/97460871-10c15980-1935-11eb-9707-15d2283b6598.png">

Is this something to do with `webpack`, too?

**Comment by glowkeeper** [comment]
Anyway, I'm getting closer! I'm trying this:

```
var {
    	Hyperdrive,
    	close
    } = await SDK({
      persist: false
    })

    const myDat = 'dat://328c78dce8a95ad7bfdc5245a99c38e71d8dc75f5671017eec7ef75049dadd6e'
    const myArchive = Hyperdrive(myDat)
    await myArchive.ready()
    console.log(await myArchive.readdir('/'))
```

That gets a lot further - unfortunately, it lists an empty array, rather than the dozen or so files I'm sharing. And I get this error, now:

<img width="1440" alt="Screenshot 2020-10-28 at 16 34 20" src="https://user-images.githubusercontent.com/9264929/97466860-7dd7ed80-193b-11eb-8191-b2dd29d25359.png">

I'm guessing I'm doing something wrong, but the docs' aren't very helpful... :(

**Comment by RangerMauve** [comment]
Hey! I'll investigate further tomorrow but I think the main issue you have right now is that the dat CLI doesn't support the latest versions of Hyperdrive. 

Essentially, stuff using the `dat://` URL scheme need an older version of the SDK (pre 2.0) or you can use something newer like `dat-store` which supports the `hyper://` protocol

**Comment by RangerMauve** [comment]
Gonna close this for now since it's been a while and there hasn't been any updates. 😅
