### ISSUE TITLE
Reuse existing identity on new node

### ISSUE THREAD

**Issue by fmsouza** [datproject/sdk#75]
I looked around the docs and issues list for a way to reuse an existing secret key on the SDK startup, but found nothing. Is it possible? And if so, how to do it?

Use case for that would be using the same identity while accessing your data on the network in different devices. Imagine a Dat based "Twitter". I want to post from several different devices (computer, phone, etc.) but using the same identity, so I won't need to have a separate feed of things I posted for each device I am using.

**Comment by DougAnderson444** [comment]
@fmsouza Fred, I believe this is in reference to the infamous multi-writer question. The Noise key in your pull request is based on the hypercore's master-key, which will be different for every device and will likely break the SDK dramatically if implemented. 

There are a few ways to do multiwriter but not with this dat-sdk:

 - hyperdrive [mounts](https://github.com/hypercore-protocol/hyperdrive#hyperdrive-mounting)
 - [kappa-core](https://github.com/kappa-db/kappa-core)
 - [kappa-multifeed](https://github.com/kappa-db/multifeed) (built on kappa-core + kappa-views)
 - [kappa-drive](https://ledger-git.dyne.org/CoBox/kappa-drive)
 - [multi-hyperbee](https://github.com/tradle/multi-hyperbee)

For example, I used kappa-multifeed to build [HyPNS](https://github.com/DougAnderson444/HyPNS) to pin identity and data in a bigger project I'm working on.

Hope that helps

**Comment by fmsouza** [comment]
Hello @DougAnderson444! Thank you very much for your response.

I read mentions about the multi-writer problem in a few discussions around hyperdrive and Dat protocol, but wasn't sure if it had anything to do with this problem I'm mentioning.

So basically what I understood from what you said is your networking identity on Dat is strictly coupled to the device you are using for access, right? So if I want to use the device as a way to access the network, but want to have a different identity, there'd need to be a second layer of identity management which would handle all the operations you'd be required to modify the contents from other nodes. Right?

But since the key is coupled to the device and I cannot change it, sounds like I cannot even create a sort of shared key which would allow me write to a node's directory from another one.

Sounds like I need to educate myself a bit more about it. Thanks for your guidance in this case, you helped a lot!

**Comment by DougAnderson444** [comment]
Yes I think you're on the right track.

In hypercore, everything is in an immutable "append-only log" writable by that device only. There is no "write on one node from another node" yet. Although there are mounts and kappa structures, which do address the issue, but as high layer solutions.

**Comment by RangerMauve** [comment]
I do multi-writer hyperdrive using https://github.com/RangerMauve/co-hyperdrive

It's being used in the Natakanu app.

Regarding re-using keys, there's a master key that gets used to derive the identity and all the named drives. You can pass this into the corestoreOpts, an example of which can be found here: https://github.com/RangerMauve/hyperdrive-publisher/blob/default/index.js#L238

**Comment by RangerMauve** [comment]
Re-using the key should only be done for restoring form backups since you'll end up forking your feed history otherwise. 😅
