### ISSUE TITLE
Hyperdrive gets stuck loading after adding a hypercore

### ISSUE THREAD

**Issue by lanmower** [datproject/sdk#82]
So I add a hyperdrive, everything works fine, add watchers and load some files and everything is hunky dory.

If I then add a hypercore (with the intention to use the extension messages) the hypercore works 100% fine, but the drive gets stuck when loading files.

The expected behavior would be that my hyperdrive keeps working after the addition of another hypercore.

**Comment by RangerMauve** [comment]
Would you mind posting a minimal test case to demonstrate this?

**Comment by RangerMauve** [comment]
Gonna close this for now since it's inactive.

Feel free to post if you'd like it reopened. 😁
